### ISSUE TITLE
Several dense tests fail when serialization is enabled

### ISSUE THREAD

**Issue by tdenniston** [Shelnutt2/TileDB#14]
Via PR #13. The following tests currently fail when serialization is added:

- "C API: Test dense array, check if coords exist in unordered writes",
- "C API: Test dense array, read subarrays with empty areas around sparse "
- "C API: Test dense array, URI ending in a slash",
- "C API: Test dense array, reset write subarray",
- "C API: Test dense array, reset read subarray",
- "C API: Test dense array, reopen array checks",
- "C API: Test dense array, open array checks",
- "C API: Test dense array, return coordinates",
- "C API: Test dense array, invalid set query buffer",
- "C API: Test dense array, non-empty domain",
- "C API: Test dense array, sparse writes",

**Comment by Shelnutt2** [comment]
@tdenniston the sparse/coordinate ones are probably blocked by these two lines:
https://github.com/Shelnutt2/TileDB/blob/98b4430cd1d6e73cf23c8363f9e807572df5cf48/tiledb/sm/query/query.cc#L333
https://github.com/Shelnutt2/TileDB/blob/98b4430cd1d6e73cf23c8363f9e807572df5cf48/tiledb/sm/query/query.cc#L567

Previously we serialized the entire array schema inside the query object too, but we stopped doing that after you pointed out it was unneeded since you have to open the array before deserializing anyway.

**Comment by tdenniston** [comment]
Reminder when these are eventually fixed, we should also add the same tests to the REST dense array tests.
